name: ci

on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        processing_version:
          - java_version: "11"
            version_prefix: "4.0b4"
          - java_version: "11"
            version_prefix: "4.0b5"
          - java_version: "11"
            version_prefix: "4.0b6"
          - java_version: "11"
            version_prefix: "4.0b7"
          - java_version: "11"
            version_prefix: "4.0b8"
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: ${{ matrix.processing_version.java_version }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            cache
          key: cache-20220720-1-${{ github.sha }}
          restore-keys: |
            cache-20220720-1-
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Pre Build
        run: |
          eval "export $(cat env/${{ matrix.processing_version.version_prefix }}.env | xargs)"
          eval "export $(cat .env | xargs)"
          ./deps.sh
          ./patch.sh apply
      - name: Build
        run: |
          sbt assembly
      - name: Cache e2e/node_modules
        uses: actions/cache@v2
        with:
          path: |
            e2e/node_modules
          key: e2e-test-node-modules-20220720-1-${{ github.sha }}
          restore-keys: |
            e2e-test-node-modules-20220720-1-
      - name: Test
        run: |
          eval "export $(cat env/${{ matrix.processing_version.version_prefix }}.env | xargs)"
          eval "export $(cat .env | xargs)"
          cd e2e
          npm ci
          npm test
        timeout-minutes: 1
      - name: Pre Deploy
        run: |
          mkdir bin
          VERSION=${{ matrix.processing_version.version_prefix }}-$(git show -s --format='%cd' --date=format:'%Y%m%d%H%M%S' HEAD)-${{ github.sha }}
          cp target/scala-3.1.0/processing-language-server-assembly-0.1.0-SNAPSHOT.jar bin/$VERSION.jar
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: processing-language-server
          path: bin/*.jar
  release:
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: processing-language-server
          path: bin/
      - name: Release
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./bin
          publish_branch: bin
          keep_files: true
