name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '11'
      - name: Build
        run: |
          ./deps
          sbt assembly
      - uses: actions/upload-artifact@v2
        with:
          name: processing-language-server-assembly-0.1.0-SNAPSHOT.jar
          path: target/scala-3.1.0/processing-language-server-assembly-0.1.0-SNAPSHOT.jar
